[workspace]
members = ["onx"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/OpenSynapsis/open-nexus"
authors = ["Gabin Noblet <gabin.noblet@gmail.com>"]